import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/pic-4.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBuld from '../../public/images/svgs/miscellaneous_icons_1 - dark.svg';
import TransitionEffect from '@/components/TransitionEffect';

const Montserrat = { subsets: ['mont'] };

export default function Home() {
  return (
    <>
      <Head>
        <title>Afzal's Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionEffect />

      <main className='flex items-centre text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="CodeBucks" className='w-full h-auto lg:hidden md:inline-block md:w-full'
              priority
              sizes='(max-width:768px) 100vw,
              (max-width:1200px) 50vw
              50vw'
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Transforming Vision into Reality:" className='!text-5xl !text-left xl:!text-5xl lg:!text-centre lg:!text-6xl md:!text-5xl sm:!text-3xl'/>
              <AnimatedText text="Where Code Meets Design." className='!text-5xl !text-left xl:!text-5xl lg:!text-centre lg:!text-6xl md:!text-5xl sm:!text-3xl'/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
              Transforming ideas into innovative web applications. Discover my portfolio of cutting-edge projects and insightful articles, showcasing expertise in web development and graphic design. As a skilled full-stack developer, I am committed to delivering exceptional digital experiences that captivate and inspire.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/dummy.pdf" target={"_blank"}
                className='flex items-center p-2.5 px-6 text-lg font-semibold md:p-2 md:px-4 md:text-base btn shadow-[0_9px_0_rgb(0,0,0)] hover:shadow-[0_4px_0px_rgb(0,0,0)] text-dark bg-Fresh dark:text-black dark:bg-Fresh ease-out hover:translate-y-1 transition-all rounded'
                download={true}
                >Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link href="mailto:afzalah747@gmail.com" target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light hover:text-Fresh md:text-base'>
                Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout> 

        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image src={lightBuld} alt="CodeBucks" className='w-full h-auto' />
        </div>
      </main>
    </>
  );
}
